# Generated by Django 5.1.7 on 2025-04-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code, e.g., USD, EUR, GBP",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Currency full name, e.g., United States Dollar",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Exchange rate from base to target currency",
                        max_digits=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date when the exchange rate was recorded"
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        help_text="Base currency (1 unit of this currency)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_rates",
                        to="currency.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        help_text="Target currency (converted value)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rates",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-date", "base_currency__code", "target_currency__code"],
                "unique_together": {("base_currency", "target_currency", "date")},
            },
        ),
    ]
