# Generated by Django 5.1.7 on 2025-04-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Exchange rate from base to target currency",
                max_digits=20,
            ),
        ),
    ]
