# Generated by Django 5.1.7 on 2025-04-14 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_alter_exchangerate_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Exchange rate from base to target currency",
                        max_digits=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date for the historical exchange rate"),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        help_text="Base currency (1 unit of this currency)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_base_rates",
                        to="currency.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        help_text="Target currency (converted value)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_target_rates",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Exchange Rate",
                "verbose_name_plural": "Historical Exchange Rates",
                "ordering": ["-date", "base_currency__code", "target_currency__code"],
                "unique_together": {("base_currency", "target_currency", "date")},
            },
        ),
    ]
