# Generated by Django 5.1.7 on 2025-04-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_historicalexchangerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatedExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Real-time exchange rate",
                        max_digits=20,
                    ),
                ),
                (
                    "calculation_rate_stored",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Calculation exchange rate",
                        max_digits=20,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this rate was stored",
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        default=None,
                        help_text="Base currency (always EUR)",
                        limit_choices_to={"code": "EUR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_base_rates",
                        to="currency.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        help_text="Target currency for the calculated rate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_target_rates",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calculated Exchange Rate",
                "verbose_name_plural": "Calculated Exchange Rates",
                "ordering": ["-date"],
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
    ]
