# Generated by Django 5.1.7 on 2025-03-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_auto_20250311_0044"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code identifying the box",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, help_text="Barcode for the box", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("FULL", "Full"),
                            ("RESERVED", "Reserved"),
                            ("IN_TRANSIT", "In Transit"),
                            ("MAINTENANCE", "Maintenance"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="AVAILABLE",
                        help_text="Current status of the box",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the box"
                    ),
                ),
            ],
            options={
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
                "ordering": ["storage_location", "code"],
            },
        ),
        migrations.CreateModel(
            name="BoxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the box type", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the box type"
                    ),
                ),
                ("length_mm", models.IntegerField(help_text="Length in millimeters")),
                ("width_mm", models.IntegerField(help_text="Width in millimeters")),
                ("height_mm", models.IntegerField(help_text="Height in millimeters")),
                (
                    "weight_capacity_g",
                    models.IntegerField(help_text="Weight capacity in grams"),
                ),
                (
                    "slot_count",
                    models.IntegerField(help_text="Number of slots in the box"),
                ),
                (
                    "slot_naming_scheme",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric (1, 2, 3...)"),
                            ("ALPHA", "Alphabetic (A, B, C...)"),
                            ("ALPHANUMERIC", "Alphanumeric (A1, A2, B1, B2...)"),
                            ("CUSTOM", "Custom scheme"),
                        ],
                        default="NUMERIC",
                        help_text="Naming scheme for slots in this box type",
                        max_length=50,
                    ),
                ),
                (
                    "custom_slot_names",
                    models.JSONField(
                        blank=True,
                        help_text="Custom slot names if using CUSTOM naming scheme",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this box type is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Box Type",
                "verbose_name_plural": "Box Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BoxSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "slot_code",
                    models.CharField(
                        help_text="Code identifying the slot within the box",
                        max_length=20,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, help_text="Barcode for the slot", max_length=100
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the slot is currently occupied",
                    ),
                ),
                (
                    "is_damaged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the slot is damaged and unusable",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the slot"
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        help_text="Box containing this slot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="inventory.box",
                    ),
                ),
            ],
            options={
                "verbose_name": "Box Slot",
                "verbose_name_plural": "Box Slots",
                "ordering": ["box", "slot_code"],
                "unique_together": {("box", "slot_code")},
            },
        ),
        migrations.AddField(
            model_name="box",
            name="box_type",
            field=models.ForeignKey(
                help_text="Type of box",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boxes",
                to="inventory.boxtype",
            ),
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country code (maps to Country in legacy system)",
                        max_length=2,
                    ),
                ),
                (
                    "city_building",
                    models.CharField(
                        blank=True,
                        help_text="City and building (maps to city_building in legacy system)",
                        max_length=100,
                    ),
                ),
                (
                    "sale",
                    models.BooleanField(
                        default=False,
                        help_text="Whether products in this location are for sale (maps to Abverkauf in legacy system)",
                    ),
                ),
                (
                    "special_spot",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a special storage spot (maps to Sonderlager in legacy system)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Storage unit identifier (maps to Regal in legacy system)",
                        max_length=50,
                    ),
                ),
                (
                    "compartment",
                    models.CharField(
                        blank=True,
                        help_text="Compartment within unit (maps to Fach in legacy system)",
                        max_length=50,
                    ),
                ),
                (
                    "shelf",
                    models.CharField(
                        blank=True,
                        help_text="Shelf identifier (maps to Boden in legacy system)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the storage location",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the storage location",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this storage location is currently active",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum capacity of the storage location (number of boxes)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Location",
                "verbose_name_plural": "Storage Locations",
                "ordering": [
                    "country",
                    "city_building",
                    "unit",
                    "compartment",
                    "shelf",
                ],
                "indexes": [
                    models.Index(
                        fields=["legacy_id"], name="inventory_s_legacy__b44a1d_idx"
                    ),
                    models.Index(
                        fields=["country", "city_building"],
                        name="inventory_s_country_8f2fb6_idx",
                    ),
                    models.Index(
                        fields=["unit", "compartment", "shelf"],
                        name="inventory_s_unit_59b9c9_idx",
                    ),
                ],
                "unique_together": {
                    ("country", "city_building", "unit", "compartment", "shelf")
                },
            },
        ),
        migrations.AddField(
            model_name="box",
            name="storage_location",
            field=models.ForeignKey(
                help_text="Storage location where the box is placed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boxes",
                to="inventory.storagelocation",
            ),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Quantity of product moved"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Inventory Receipt"),
                            ("ISSUE", "Inventory Issue"),
                            ("TRANSFER", "Internal Transfer"),
                            ("ADJUSTMENT", "Inventory Adjustment"),
                            ("RETURN", "Customer Return"),
                            ("SCRAP", "Scrap/Disposal"),
                        ],
                        help_text="Type of inventory movement",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number (e.g., order number, transfer ID)",
                        max_length=100,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of reference (e.g., Sales Order, Purchase Order)",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the movement"
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="User who performed the movement",
                        max_length=100,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of the movement"
                    ),
                ),
                (
                    "from_slot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source box slot (null for new inventory)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_movements",
                        to="inventory.boxslot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being moved",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="products.variantproduct",
                    ),
                ),
                (
                    "to_slot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination box slot (null for inventory removal)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_movements",
                        to="inventory.boxslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Movement",
                "verbose_name_plural": "Inventory Movements",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="inventory_i_product_2153f2_idx"
                    ),
                    models.Index(
                        fields=["movement_type"], name="inventory_i_movemen_e5f549_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="inventory_i_referen_a31c3e_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="inventory_i_timesta_1796ae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Quantity of the product in this location"
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved for Order"),
                            ("ALLOCATED", "Allocated for Production"),
                            ("QUALITY_HOLD", "Quality Control Hold"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="AVAILABLE",
                        help_text="Reservation status of the product",
                        max_length=20,
                    ),
                ),
                (
                    "reservation_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for the reservation (e.g., order number)",
                        max_length=100,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of the product, if applicable",
                        null=True,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Batch or lot number of the product",
                        max_length=100,
                    ),
                ),
                (
                    "date_stored",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the product was stored in this location",
                    ),
                ),
                (
                    "box_slot",
                    models.ForeignKey(
                        help_text="Box slot where the product is stored",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_products",
                        to="inventory.boxslot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product stored in this location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_locations",
                        to="products.variantproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Storage",
                "verbose_name_plural": "Product Storage",
                "ordering": ["-date_stored"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="inventory_p_product_103f35_idx"
                    ),
                    models.Index(
                        fields=["reservation_status"],
                        name="inventory_p_reserva_11387a_idx",
                    ),
                    models.Index(
                        fields=["batch_number"], name="inventory_p_batch_n_3dee34_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["code"], name="inventory_b_code_0d4e47_idx"),
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["status"], name="inventory_b_status_dd318d_idx"),
        ),
    ]
