# Generated by Django 5.1.7 on 2025-03-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxtype",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height of the box in cm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length of the box in cm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="weight_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum weight capacity in kg",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width of the box in cm",
                max_digits=6,
                null=True,
            ),
        ),
    ]
