# Generated by Django 5.1.7 on 2025-03-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxslot",
            name="max_products",
            field=models.IntegerField(
                default=100,
                help_text="Maximum number of different products that can be stored in this slot",
            ),
        ),
        migrations.AddField(
            model_name="productstorage",
            name="position_in_slot",
            field=models.CharField(
                blank=True,
                help_text="Position identifier within the slot (e.g., front, back, left, right)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="productstorage",
            index=models.Index(
                fields=["box_slot"], name="inventory_p_box_slo_96c05c_idx"
            ),
        ),
    ]
