# Generated by Django 5.1.6 on 2025-03-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="product",
            field=models.ForeignKey(
                help_text="Product being moved",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_movements",
                to="products.variantproduct",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="to_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Box slot the product is moved to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_movements",
                to="inventory.boxslot",
            ),
        ),
        migrations.AddField(
            model_name="productstorage",
            name="product",
            field=models.ForeignKey(
                help_text="Product stored in this location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_locations",
                to="products.variantproduct",
            ),
        ),
        migrations.AddField(
            model_name="boxstorage",
            name="product_storage",
            field=models.ForeignKey(
                help_text="Product storage record (maps to UUID_Artikel_Lagerorte in legacy system)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_assignments",
                to="inventory.productstorage",
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(
                fields=["legacy_id"], name="inventory_s_legacy__b44a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(
                fields=["country", "city_building"],
                name="inventory_s_country_8f2fb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(
                fields=["unit", "compartment", "shelf"],
                name="inventory_s_unit_59b9c9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storagelocation",
            unique_together={
                ("country", "city_building", "unit", "compartment", "shelf")
            },
        ),
        migrations.AddField(
            model_name="productstorage",
            name="storage_location",
            field=models.ForeignKey(
                help_text="Storage location where the product is stored",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_products",
                to="inventory.storagelocation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boxslot",
            unique_together={("box", "slot_code")},
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["code"], name="inventory_b_code_0d4e47_idx"),
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["status"], name="inventory_b_status_dd318d_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["product"], name="inventory_i_product_2153f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_i_movemen_e5f549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["timestamp"], name="inventory_i_timesta_1796ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boxstorage",
            index=models.Index(
                fields=["product_storage"], name="inventory_b_product_50b592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boxstorage",
            index=models.Index(
                fields=["box_slot"], name="inventory_b_box_slo_0c5188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boxstorage",
            index=models.Index(
                fields=["batch_number"], name="inventory_b_batch_n_c1550e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boxstorage",
            unique_together={
                ("box_slot", "product_storage", "batch_number", "position_in_slot")
            },
        ),
        migrations.AddIndex(
            model_name="productstorage",
            index=models.Index(
                fields=["product"], name="inventory_p_product_103f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstorage",
            index=models.Index(
                fields=["storage_location"], name="inventory_p_storage_801eb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstorage",
            index=models.Index(
                fields=["reservation_status"], name="inventory_p_reserva_11387a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productstorage",
            unique_together={("product", "storage_location")},
        ),
    ]
