# Generated by Django 5.1.7 on 2025-03-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={
                "ordering": ["code"],
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
            },
        ),
        migrations.RemoveIndex(
            model_name="inventorymovement",
            name="inventory_i_referen_a31c3e_idx",
        ),
        migrations.RenameField(
            model_name="boxslot",
            old_name="is_occupied",
            new_name="occupied",
        ),
        migrations.RemoveField(
            model_name="boxslot",
            name="is_damaged",
        ),
        migrations.RemoveField(
            model_name="boxslot",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="custom_slot_names",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="height_mm",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="length_mm",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="weight_capacity_g",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="width_mm",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="reference_type",
        ),
        migrations.AddField(
            model_name="boxtype",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height of the box in cm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boxtype",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length of the box in cm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boxtype",
            name="weight_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum weight capacity in kg",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boxtype",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width of the box in cm",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Reference for the movement (e.g., order number)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="location_code",
            field=models.CharField(
                blank=True,
                help_text="Formatted location code (maps to Lagerort in legacy system)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="code",
            field=models.CharField(help_text="Unique code for the box", max_length=50),
        ),
        migrations.AlterField(
            model_name="box",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_USE", "In Use"),
                    ("RESERVED", "Reserved"),
                    ("DAMAGED", "Damaged"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                help_text="Current status of the box",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="boxslot",
            name="slot_code",
            field=models.CharField(
                help_text="Code for the slot within the box", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the box type"),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="slot_count",
            field=models.IntegerField(
                default=1, help_text="Number of slots in this box type"
            ),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="slot_naming_scheme",
            field=models.CharField(
                default="numeric",
                help_text="Naming scheme for slots (numeric, alphabetic, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="from_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Box slot the product is moved from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_movements",
                to="inventory.boxslot",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Receipt"),
                    ("TRANSFER", "Transfer"),
                    ("PICK", "Pick"),
                    ("RETURN", "Return"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("DISPOSAL", "Disposal"),
                ],
                help_text="Type of movement",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.IntegerField(help_text="Quantity of the product moved"),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="to_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Box slot the product is moved to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_movements",
                to="inventory.boxslot",
            ),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="Batch or lot number for the product",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="date_stored",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when the product was stored"
            ),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Expiry date for the product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="reservation_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference for the reservation (e.g., order number)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productstorage",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("RESERVED", "Reserved"),
                    ("ALLOCATED", "Allocated"),
                    ("PICKED", "Picked"),
                ],
                default="AVAILABLE",
                help_text="Current reservation status of the product",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="city_building",
            field=models.CharField(
                blank=True,
                help_text="City and building (maps to Ort_Gebaeude in legacy system)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country code (maps to Land_LKZ in legacy system)",
                max_length=2,
            ),
        ),
    ]
