# Generated by Django 5.1.7 on 2025-03-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_boxslot_max_products_productstorage_position_in_slot_and_more",
        ),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productstorage",
            unique_together={
                ("box_slot", "product", "batch_number", "position_in_slot")
            },
        ),
    ]
