# Generated by Django 5.1.7 on 2025-03-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_boxtype_height_alter_boxtype_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Storage location where the box is placed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boxes",
                to="inventory.storagelocation",
            ),
        ),
    ]
