# Generated by Django 5.1.7 on 2025-03-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current storage location of the box",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boxes",
                to="inventory.storagelocation",
            ),
        ),
    ]
