# Generated by Django 5.1.7 on 2025-03-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_box_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("STORAGE", "Storage"),
                    ("PICKING", "Picking"),
                    ("TRANSPORT", "Transport"),
                    ("WORKSHOP", "Workshop"),
                ],
                default="STORAGE",
                help_text="Primary purpose of this box",
                max_length=20,
            ),
        ),
    ]
