# Generated by Django 5.1.7 on 2025-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_allow_null_storage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxslot",
            name="color_code",
            field=models.CharField(
                blank=True,
                help_text="Color code identifier (maps to Einheitenfabe in legacy system)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="boxslot",
            name="legacy_slot_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier from legacy system (ID_Lager_Schuetten_Slots)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boxslot",
            name="order_number",
            field=models.CharField(
                blank=True,
                help_text="Associated order number (maps to Auftrags_Nr in legacy system)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="boxslot",
            name="slot_number",
            field=models.IntegerField(
                default=1,
                help_text="Sequential number within the box (maps to Lfd_Nr in legacy system)",
            ),
        ),
        migrations.AddField(
            model_name="boxslot",
            name="unit_number",
            field=models.IntegerField(
                default=1,
                help_text="Unit number within the slot (maps to Einheiten_Nr in legacy system)",
            ),
        ),
    ]
