# Generated by Django 5.1.7 on 2025-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_box_storage_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagelocation",
            name="capacity",
        ),
        migrations.AddField(
            model_name="boxslot",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum capacity of the slot (number of items)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="box_capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of boxes that can be stored in this location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="capacity_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum total capacity limit for this location",
                null=True,
            ),
        ),
    ]
