# Generated by Django 5.1.7 on 2025-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_restructure_storage_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxtype",
            name="slot_naming_scheme",
            field=models.CharField(
                default="numeric",
                help_text="Scheme for naming slots (e.g., numeric, alphabetic)",
                max_length=50,
            ),
        ),
    ] 