# Generated by Django 5.1.7 on 2025-03-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_storagelocation_capacity_boxslot_capacity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boxstorage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this box storage record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="box_storage_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum storage capacity in standard units",
                null=True,
            ),
        ),
    ]
