# Generated by Django 5.1.7 on 2025-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_boxstorage_created_by_storagelocation_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxstorage",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="Batch or lot number for the product",
                max_length=100,
                null=True,
            ),
        ),
    ]
