name: parent_product_sync
description: Synchronize parent products from legacy system

source:
  type: api
  extractor: LegacyAPIExtractor
  config:
    environment: live
    table_name: Artikel_Familie
    filters:
      active: true
    page_size: 100

transformation:
  transformer: ProductTransformer
  field_mappings:
    __KEY: legacy_id
    Nummer: sku
    Nummer: base_sku
    Bezeichnung: name
    Bezeichnung_ENG: name_en
    Beschreibung: description
    Beschreibung_ENG: description_en
    Beschreibung_kurz: short_description
    Beschreibung_kurz_ENG: short_description_en
    Gewicht: weight
    ArtGr: category_code
    Haengend: is_hanging
    Einseitig: is_one_sided
  custom_transformers:
    - transform_dimensions
    - transform_boolean_flags
  validation_rules:
    - field: sku
      validator: validate_sku_format
      error_message: Invalid SKU format
    - field: name
      validator: validate_not_empty
      error_message: Name cannot be empty
    - field: weight
      validator: validate_non_negative
      error_message: Weight must be non-negative

target:
  loader: DjangoModelLoader
  config:
    app_name: pyerp.products
    model_name: ParentProduct
    unique_field: sku
    conflict_strategy: newest_wins

scheduling:
  frequency: daily
  time: '02:00'
  dependencies:
    - category_sync

incremental:
  enabled: true
  timestamp_field: last_modified
  full_sync_fallback: true 