---
# Sales Record Synchronization Configuration

# Sales Records Sync (Belege)
sales_records:
  name: "Sales Records Sync"
  description: "Synchronize sales records from legacy Belege table"
  source:
    type: "legacy_api"
    extractor_class: "pyerp.sync.extractors.legacy_api.LegacyAPIExtractor"
    config:
      environment: "live"
      table_name: "Belege"
      page_size: 100
  transformer:
    type: "custom"
    class: "pyerp.sync.transformers.sales_record.SalesRecordTransformer"
    config:
      field_mappings:
        legacy_id: "AbsNr"
        record_number: "PapierNr"
        record_date: 
          field: "Datum"
          transform: "parse_legacy_date"
        record_type:
          field: "Papierart"
          transform: "map_record_type"
        customer:
          field: "KundenNr"
          lookup:
            model: "pyerp.business_modules.sales.models.Customer"
            field: "legacy_id"
        subtotal:
          field: "Netto"
          transform: "to_decimal"
        tax_amount:
          field: "MWST_EUR"
          transform: "to_decimal"
        shipping_cost:
          field: "Frachtkosten"
          transform: "to_decimal"
        handling_fee:
          field: "Bearbeitungskos"
          transform: "to_decimal"
        total_amount:
          field: "Endbetrag"
          transform: "to_decimal"
        payment_status: "bezahlt"
        payment_date:
          field: "ZahlungsDat"
          transform: "parse_legacy_date"
        currency:
          field: "Währung"
          transform: "map_currency"
        tax_type: "MWSt_Art"
        notes: "Text"
      lookups:
        payment_terms:
          model: "pyerp.business_modules.sales.models.PaymentTerms"
          fields:
            days_due:
              field: "NettoTage"
              default: 30
            discount_days:
              field: "SkontoTage"
              default: 0
            discount_percent:
              field: "Skonto_G"
              transform: "to_decimal"
              default: 0
          get_or_create: true
        payment_method:
          model: "pyerp.business_modules.sales.models.PaymentMethod"
          fields:
            name:
              field: "Zahlungsart_A"
              default: "Invoice"
            code:
              field: "Zahlungsart_A"
              transform: "slugify"
              default: "invoice"
          get_or_create: true
        shipping_method:
          model: "pyerp.business_modules.sales.models.ShippingMethod"
          fields:
            name:
              field: "Versandart"
              default: "Standard"
            code:
              field: "Versandart"
              transform: "slugify"
              default: "standard"
          get_or_create: true
  loader:
    type: "django_model"
    class: "pyerp.sync.loaders.django_model.DjangoModelLoader"
    config:
      app_name: "sales"
      model_name: "SalesRecord"
      unique_field: "legacy_id"
      update_strategy: "update_or_create"
  schedule:
    frequency: "hourly"
    time: "*/15"  # Every 15 minutes
  incremental:
    enabled: true
    timestamp_field: "modified_date"
    timestamp_filter_format: "modified_date > {value}"
  default_filters:
    date_range:
      field: "Datum"
      years: 5  # Last 5 years
  related_entities:
    - "sales_record_items"

# Sales Record Items Sync (Belege_Pos)
sales_record_items:
  name: "Sales Record Items Sync"
  description: "Synchronize sales record line items from legacy Belege_Pos table"
  source:
    type: "legacy_api"
    extractor_class: "pyerp.sync.extractors.legacy_api.LegacyAPIExtractor"
    config:
      environment: "live"
      table_name: "Belege_Pos"
      page_size: 200
  transformer:
    type: "custom"
    class: "pyerp.sync.transformers.sales_record.SalesRecordTransformer"
    config:
      transform_method: "transform_line_items"
      field_mappings:
        position: "PosNr"
        product_code: "ArtNr"
        description: "Bezeichnung"
        quantity:
          field: "Menge"
          transform: "to_decimal"
        unit_price:
          field: "Preis"
          transform: "to_decimal"
        discount_percentage:
          field: "Rabatt"
          transform: "to_decimal"
        line_total:
          field: "Pos_Betrag"
          transform: "to_decimal"
        item_type:
          field: "Art"
          transform: "map_item_type"
        fulfilled_quantity:
          field: "Pick_Menge"
          transform: "to_decimal"
      lookups:
        product:
          model: "pyerp.business_modules.products.models.Product"
          fields:
            product_code: "ArtNr"
          get_or_create: false
          required: false
      composite_key: ["AbsNr", "PosNr"]
  loader:
    type: "django_model"
    class: "pyerp.sync.loaders.django_model.DjangoModelLoader"
    config:
      app_name: "sales"
      model_name: "SalesRecordItem"
      unique_field: "legacy_id"
      update_strategy: "update_or_create"
      parent_field: "sales_record"
      parent_mapping: "sales_records"
  schedule:
    frequency: "hourly"
    time: "*/15"  # Every 15 minutes
  incremental:
    enabled: true
    timestamp_field: "modified_date"
    timestamp_filter_format: "modified_date > {value}"
  filter_strategy:
    type: "parent_ids"
    parent_field: "AbsNr"
    parent_entity: "sales_records"
  dependencies:
    - "sales_records"
    - "products"

# Combined Sales Record Sync
sales_record_sync:
  name: "Complete Sales Record Sync"
  description: "Combined sales record and line items sync process"
  components:
    - "sales_records"
    - "sales_record_items"
  schedule:
    frequency: "daily"
    time: "03:00"  # 3 AM
  dependencies:
    - "customers"
    - "products" 