site_name: pyERP Documentation
site_url: https://example.com/
repo_url: https://github.com/your-org/pyERP/
repo_name: your-org/pyERP

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            members_order: source

nav:
  - Home: index.md
  - API:
      - "Swagger UI (Dev)": "http://localhost:8000/api/swagger/"
      - "Swagger UI (Prod)": "/api/swagger/"
  - Entwicklung:
      - Setup: development/setup.md
      - Docker: development/docker_deployment.md
      - Lokalisierung: development/localization_best_practices.md
      - Umgebungskonfiguration: environment_configuration.md
      - Abhängigkeiten: 
        - Management: dependency_management.md
        - Updates: dependency_updates.md
  - Features:
      - Inventory & Warehouse: features/inventory_warehouse_management.md
      - Product Image Sync: features/product_image_sync.md
  - Implementation:
      - Datenbank: implementation/database_internationalization.md
      - Internationalisierung: 
        - Übersicht: implementation/internationalization.md
        - Aufgabenliste: implementation/i18n_task_list.md
      - JWT Auth: 
        - Guide: implementation/jwt_auth_implementation_guide.md
        - Plan: implementation/jwt_auth_implementation_plan.md
      - Produkt-Modul: implementation/product_module_progress.md
  - Testing:
      - Übersicht: testing.md
      - Zusammenfassung: testing_summary.md
      - Coverage: 
        - Report: test_coverage_report.md
        - Verbesserungsplan: test_coverage_improvement_plan.md
      - Property Based Testing: property_based_testing.md
      - Mutation Testing: mutation_testing.md
      - React Testing:
        - Fixes: react_testing_fixes.md
        - Verbesserungsplan: react_testing_improvement_plan.md
  - Sicherheit:
      - Übersicht: security/README.md
      - Audit Logging: security/audit_logging.md
  - Deployment: DEPLOYMENT.md
  - Monitoring: monitoring.md
  - Contributing: CONTRIBUTING.md
  - Project Structure: project_structure.md
  - Frameworks & Plugins: frameworks_and_plugins.md
  - API Reference:
      - pyerp Core: api/pyerp.md
      - Components: api/components.md
      # Add other relevant markdown files from the `docs` directory as needed
      # Example:
      # - Features:
      #   - Inventory Management: features/inventory_warehouse_management.md
      #   - Product Image Sync: features/product_image_sync.md
      # - Implementation Guides:
      #   - Internationalization: implementation/internationalization.md
      #   - JWT Auth: implementation/jwt_auth_implementation_guide.md
      # - Development:
      #   - Docker: development/docker_deployment.md
      # Beispiel:
      # - pyerp/: api/pyerp/
      # - components/: api/components/ 