import pandas as pd

# ... existing code ...
merged_product_locations = pd.merge(product_locations, merged_locations, left_on='UUID', right_on='UUID_Artikel_Lagerorte', how='outer')
# ... existing code ... 