"""
Constants for the Images CMS API.
"""

# Constants for image processing
MIN_THUMBNAIL_RESOLUTION = 150
MAX_THUMBNAIL_RESOLUTION = 300
MIN_RESOLUTION_ARRAY_LENGTH = 2

# API configuration constants
DEFAULT_TIMEOUT = 60  # seconds
DEFAULT_CACHE_TIMEOUT = 3600  # 1 hour
DEFAULT_PAGE_SIZE = 50
MAX_RETRIES = 3
BACKOFF_FACTOR = 0.5
RETRY_STATUS_CODES = [500, 502, 503, 504]
HTTP_OK = 200
