# Generated by Django 5.1.6 on 2025-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheckresult",
            name="component",
            field=models.CharField(
                choices=[
                    ("database", "Database"),
                    ("legacy_erp", "Legacy ERP"),
                    ("images_cms", "Images CMS"),
                    ("database_validation", "Database Validation"),
                ],
                help_text="System component being checked",
                max_length=50,
                verbose_name="Component",
            ),
        ),
    ]
