# Generated by Django 4.2.11 on 2025-02-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_parent',
            field=models.BooleanField(default=False, help_text='Whether this is a parent product (maps to Art_Kalkulation records)'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent product (for variants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hanging',
            field=models.BooleanField(default=False, help_text='Whether the product is hanging (maps to haengen in legacy system)'),
        ),
    ]
