# Generated by Django 5.1.6 on 2025-03-04 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='backorder_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on backorder'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price (maps to Einkauf price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description (maps to Beschreibung in legacy system)'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='description_en',
            field=models.TextField(blank=True, help_text='Full product description in English'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions (LxWxH)', max_length=50),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recommended retail price (maps to Empf. price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='has_bom',
            field=models.BooleanField(default=False, help_text='Whether the product has a bill of materials'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Whether the product is discontinued'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='is_hanging',
            field=models.BooleanField(default=False, help_text='Whether the product is hanging'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='is_one_sided',
            field=models.BooleanField(default=False, help_text='Whether the product is one-sided'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='keywords',
            field=models.CharField(blank=True, help_text='Search keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='last_issue_date',
            field=models.DateField(blank=True, help_text='Date of last stock issue', null=True),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='last_receipt_date',
            field=models.DateField(blank=True, help_text='Date of last stock receipt', null=True),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='legacy_uid',
            field=models.CharField(blank=True, help_text='UID in the legacy system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retail price (maps to Laden price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='min_stock_quantity',
            field=models.IntegerField(default=0, help_text='Minimum stock quantity before reordering'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='name_en',
            field=models.CharField(blank=True, help_text='Product name in English (maps to Bezeichnung_ENG in legacy system)', max_length=255),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='open_purchase_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on open purchase orders'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='revenue_previous_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue in previous year', max_digits=12),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short product description (maps to Beschreibung_kurz in legacy system)'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Short product description in English'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='units_sold_current_year',
            field=models.IntegerField(default=0, help_text='Units sold in current year'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='units_sold_previous_year',
            field=models.IntegerField(default=0, help_text='Units sold in previous year'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight in grams', null=True),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price (maps to Handel price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='backorder_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on backorder'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price (maps to Einkauf price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description (maps to Beschreibung in legacy system)'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='description_en',
            field=models.TextField(blank=True, help_text='Full product description in English'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions (LxWxH)', max_length=50),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recommended retail price (maps to Empf. price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='has_bom',
            field=models.BooleanField(default=False, help_text='Whether the product has a bill of materials'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Whether the product is discontinued'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_hanging',
            field=models.BooleanField(default=False, help_text='Whether the product is hanging'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_one_sided',
            field=models.BooleanField(default=False, help_text='Whether the product is one-sided'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='keywords',
            field=models.CharField(blank=True, help_text='Search keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='last_issue_date',
            field=models.DateField(blank=True, help_text='Date of last stock issue', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='last_receipt_date',
            field=models.DateField(blank=True, help_text='Date of last stock receipt', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_uid',
            field=models.CharField(blank=True, help_text='UID in the legacy system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retail price (maps to Laden price in legacy system)', max_digits=10),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='min_stock_quantity',
            field=models.IntegerField(default=0, help_text='Minimum stock quantity before reordering'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='name_en',
            field=models.CharField(blank=True, help_text='Product name in English (maps to Bezeichnung_ENG in legacy system)', max_length=255),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='open_purchase_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on open purchase orders'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='revenue_previous_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue in previous year', max_digits=12),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short product description (maps to Beschreibung_kurz in legacy system)'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Short product description in English'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='units_sold_current_year',
            field=models.IntegerField(default=0, help_text='Units sold in current year'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight in grams', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='last_synced',
            field=models.DateTimeField(auto_now=True, help_text='When this image record was last updated'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='last_ordered_date',
            field=models.DateField(blank=True, help_text='Date of last customer order', null=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (maps to ArtNr in legacy system)', max_length=50, unique=True)),
                ('base_sku', models.CharField(db_index=True, help_text='Base SKU without variant (maps to fk_ArtNr in legacy system)', max_length=50)),
                ('variant_code', models.CharField(blank=True, help_text='Variant code (maps to ArtikelArt in legacy system)', max_length=10)),
                ('legacy_id', models.CharField(blank=True, help_text='ID in the legacy system', max_length=50, null=True, unique=True)),
                ('legacy_sku', models.CharField(blank=True, help_text='Legacy SKU (maps to alteNummer in Artikel_Variante)', max_length=50, null=True)),
                ('is_parent', models.BooleanField(default=False, help_text='Whether this is a parent product (maps to Art_Kalkulation records)')),
                ('name', models.CharField(help_text='Product name (maps to Bezeichnung in legacy system)', max_length=255)),
                ('name_en', models.CharField(blank=True, help_text='Product name in English (maps to Bezeichnung_ENG in legacy system)', max_length=255)),
                ('short_description', models.TextField(blank=True, help_text='Short product description (maps to Beschreibung_kurz in legacy system)')),
                ('short_description_en', models.TextField(blank=True, help_text='Short product description in English')),
                ('description', models.TextField(blank=True, help_text='Full product description (maps to Beschreibung in legacy system)')),
                ('description_en', models.TextField(blank=True, help_text='Full product description in English')),
                ('keywords', models.CharField(blank=True, help_text='Search keywords', max_length=255)),
                ('dimensions', models.CharField(blank=True, help_text='Product dimensions (LxWxH)', max_length=50)),
                ('weight', models.IntegerField(blank=True, help_text='Weight in grams', null=True)),
                ('list_price', models.DecimalField(decimal_places=2, default=0, help_text='Retail price (maps to Laden price in legacy system)', max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price (maps to Handel price in legacy system)', max_digits=10)),
                ('gross_price', models.DecimalField(decimal_places=2, default=0, help_text='Recommended retail price (maps to Empf. price in legacy system)', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price (maps to Einkauf price in legacy system)', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('min_stock_quantity', models.IntegerField(default=0, help_text='Minimum stock quantity before reordering')),
                ('backorder_quantity', models.IntegerField(default=0, help_text='Quantity on backorder')),
                ('open_purchase_quantity', models.IntegerField(default=0, help_text='Quantity on open purchase orders')),
                ('last_receipt_date', models.DateField(blank=True, help_text='Date of last stock receipt', null=True)),
                ('last_issue_date', models.DateField(blank=True, help_text='Date of last stock issue', null=True)),
                ('units_sold_current_year', models.IntegerField(default=0, help_text='Units sold in current year')),
                ('units_sold_previous_year', models.IntegerField(default=0, help_text='Units sold in previous year')),
                ('revenue_previous_year', models.DecimalField(decimal_places=2, default=0, help_text='Revenue in previous year', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active')),
                ('is_discontinued', models.BooleanField(default=False, help_text='Whether the product is discontinued')),
                ('has_bom', models.BooleanField(default=False, help_text='Whether the product has a bill of materials')),
                ('is_one_sided', models.BooleanField(default=False, help_text='Whether the product is one-sided')),
                ('is_hanging', models.BooleanField(default=False, help_text='Whether the product is hanging')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent product (for variants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
