# Generated by Django 4.2.11 on 2025-02-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_imagesynclog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantProduct',
        ),
        migrations.DeleteModel(
            name='ParentProduct',
        ),
    ]
