# Generated by Django 5.1.6 on 2025-03-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentproduct",
            name="is_placeholder",
        ),
    ]
