# Generated by Django 4.2.11 on 2025-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_parent_product_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the sync process started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sync process completed', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', help_text='Current status of the sync process', max_length=20)),
                ('images_added', models.IntegerField(default=0, help_text='Number of new images added')),
                ('images_updated', models.IntegerField(default=0, help_text='Number of existing images updated')),
                ('images_deleted', models.IntegerField(default=0, help_text='Number of images deleted')),
                ('products_affected', models.IntegerField(default=0, help_text='Number of products affected by the sync')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the sync failed')),
            ],
            options={
                'verbose_name': 'Image Sync Log',
                'verbose_name_plural': 'Image Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='external_id',
            field=models.CharField(default='legacy', help_text='ID from external image database', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='unknown', help_text='Type of image (e.g., "Produktfoto")', max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='', help_text='URL to the full-size image', max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_front',
            field=models.BooleanField(default=False, help_text='Whether this image is marked as "front" in the source system'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='last_synced',
            field=models.DateTimeField(auto_now=True, help_text='When the image was last synced from the external system'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from the source system'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.IntegerField(default=0, help_text='Display priority (lower numbers shown first)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to the thumbnail image', max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['external_id'], name='products_pr_externa_7c270c_idx'),
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
    ]
