# Generated by Django 4.2.11 on 2025-02-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (maps to Nummer in legacy system)', max_length=50, unique=True)),
                ('legacy_id', models.CharField(blank=True, help_text='ID in the legacy system (maps to __KEY)', max_length=50, null=True, unique=True)),
                ('legacy_uid', models.CharField(blank=True, help_text='UID in the legacy system', max_length=50, null=True)),
                ('__KEY', models.CharField(blank=True, help_text='Original __KEY from legacy system', max_length=50, null=True)),
                ('UID', models.CharField(blank=True, help_text='Original UID from legacy system', max_length=50, null=True)),
                ('name', models.CharField(help_text='Product name (maps to Bezeichnung in legacy system)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active')),
                ('base_sku', models.CharField(db_index=True, help_text='Base SKU for variants', max_length=50)),
            ],
            options={
                'verbose_name': 'Parent Product',
                'verbose_name_plural': 'Parent Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VariantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (maps to Nummer in legacy system)', max_length=50, unique=True)),
                ('legacy_id', models.CharField(blank=True, help_text='ID in the legacy system (maps to __KEY)', max_length=50, null=True, unique=True)),
                ('legacy_uid', models.CharField(blank=True, help_text='UID in the legacy system', max_length=50, null=True)),
                ('__KEY', models.CharField(blank=True, help_text='Original __KEY from legacy system', max_length=50, null=True)),
                ('UID', models.CharField(blank=True, help_text='Original UID from legacy system', max_length=50, null=True)),
                ('FAMILIE_', models.CharField(blank=True, help_text='Original FAMILIE_ reference from legacy system', max_length=50, null=True)),
                ('name', models.CharField(help_text='Product name (maps to Bezeichnung in legacy system)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active')),
                ('variant_code', models.CharField(blank=True, help_text='Variant code', max_length=10)),
                ('legacy_sku', models.CharField(blank=True, help_text='Legacy SKU (maps to alteNummer in Artikel_Variante)', max_length=50, null=True)),
                ('base_sku', models.CharField(db_index=True, help_text='Base SKU without variant', max_length=50)),
                ('parent', models.ForeignKey(help_text='Parent product (maps to Familie_ in legacy system)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.parentproduct')),
            ],
            options={
                'verbose_name': 'Variant Product',
                'verbose_name_plural': 'Variant Products',
                'ordering': ['parent__name', 'variant_code'],
            },
        ),
    ]
