# Generated by Django 5.1.6 on 2025-03-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_parentproduct_backorder_quantity_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_parentproduct 
            ALTER COLUMN is_active TYPE boolean 
            USING CASE WHEN is_active = 0 THEN false 
                      WHEN is_active = 1 THEN true 
                      ELSE null END;
            
            ALTER TABLE products_variantproduct 
            ALTER COLUMN is_active TYPE boolean 
            USING CASE WHEN is_active = 0 THEN false 
                      WHEN is_active = 1 THEN true 
                      ELSE null END;
            """,
            reverse_sql="""
            ALTER TABLE products_parentproduct 
            ALTER COLUMN is_active TYPE smallint 
            USING CASE WHEN is_active THEN 1 
                      ELSE 0 END;
            
            ALTER TABLE products_variantproduct 
            ALTER COLUMN is_active TYPE smallint 
            USING CASE WHEN is_active THEN 1 
                      ELSE 0 END;
            """
        ),
    ]
