# Generated by Django 4.2.11 on 2025-02-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recreate_product_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='parentproduct',
            name='__KEY',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='FAMILIE_',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='__KEY',
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='ID in the legacy system - maps directly to __KEY in Artikel_Variante/Artikel_Familie', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='legacy_uid',
            field=models.CharField(blank=True, help_text='UID in the legacy system - maps directly to UID in Artikel_Variante/Artikel_Familie', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='ID in the legacy system - maps directly to __KEY in Artikel_Variante/Artikel_Familie', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='legacy_uid',
            field=models.CharField(blank=True, help_text='UID in the legacy system - maps directly to UID in Artikel_Variante/Artikel_Familie', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='parent',
            field=models.ForeignKey(help_text='Parent product - maps to Familie_ field in Artikel_Variante which references __KEY in Artikel_Familie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.parentproduct'),
        ),
    ]
