# Generated by Django 5.1.6 on 2025-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_parentproduct_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, help_text='Whether the product is active'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, help_text='Whether the product is active'),
        ),
    ]
