# Generated by Django 4.2.11 on 2025-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_imagesynclog_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_sku',
            field=models.CharField(blank=True, help_text='Legacy SKU (maps to alteNummer in Artikel_Variante)', max_length=50, null=True),
        ),
    ]
