# Generated by Django 4.2.11 on 2025-02-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_migrate_data_to_new_tables'),
        ('products', '0004_product_legacy_sku'),
    ]

    operations = [
    ]
