# Generated by Django 5.1.6 on 2025-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_parentproduct_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesynclog',
            name='id',
            field=models.BigAutoField(primary_key=True),
        ),
    ]
