# Generated by Django 4.2.11 on 2025-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_parentproduct_uid_remove_parentproduct___key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_familie',
            field=models.CharField(blank=True, db_column='Familie_', help_text='Original Familie_ field from Artikel_Variante', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_key',
            field=models.CharField(blank=True, db_column='__KEY', help_text='Original __KEY field from Artikel_Variante', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_uid_original',
            field=models.CharField(blank=True, db_column='UID', help_text='Original UID field from Artikel_Variante', max_length=50, null=True),
        ),
    ]
