# Generated by Django 5.1.6 on 2025-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_imagesynclog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesynclog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
