# Generated by Django 4.2.11 on 2025-02-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_20250227_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_base_sk_1718b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='backorder_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on backorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price (maps to Einkauf price in legacy system)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description (maps to Beschreibung in legacy system)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Full product description in English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions (LxWxH)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recommended retail price (maps to Empf. price in legacy system)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_bom',
            field=models.BooleanField(default=False, help_text='Whether the product has a bill of materials'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Whether the product is discontinued'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hanging',
            field=models.BooleanField(default=False, help_text='Whether the product is hanging'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_one_sided',
            field=models.BooleanField(default=False, help_text='Whether the product is one-sided'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text='Search keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_issue_date',
            field=models.DateField(blank=True, help_text='Date of last stock issue', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_receipt_date',
            field=models.DateField(blank=True, help_text='Date of last stock receipt', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retail price (maps to Laden price in legacy system)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_quantity',
            field=models.IntegerField(default=0, help_text='Minimum stock quantity before reordering'),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_purchase_quantity',
            field=models.IntegerField(default=0, help_text='Quantity on open purchase orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='revenue_previous_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue in previous year', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Short product description in English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_sold_current_year',
            field=models.IntegerField(default=0, help_text='Units sold in current year'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_sold_previous_year',
            field=models.IntegerField(default=0, help_text='Units sold in previous year'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight in grams', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price (maps to Handel price in legacy system)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(help_text='Unique category code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
