# Generated by Django 4.2.11 on 2025-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variantproduct_legacy_familie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='Indicates if this is a placeholder parent created for orphaned variants'),
        ),
    ]
