# Generated by Django 4.2.11 on 2025-02-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_parentproduct_is_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='legacy_uid',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_key',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_uid',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_uid_original',
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='ID in the legacy system - maps directly to __KEY and UID in legacy system (which had identical values)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='ID in the legacy system - maps directly to __KEY and UID in legacy system (which had identical values)', max_length=50, null=True, unique=True),
        ),
    ]
