# Generated by Django 4.2.11 on 2025-02-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_redundant_legacy_fields'),
    ]

    operations = [
        # Run raw SQL to ensure columns are actually dropped from the database
        migrations.RunSQL(
            sql=[
                # First, check if the column exists in the information schema before dropping
                """
                SET @query = IF(EXISTS(
                    SELECT * FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'products_variantproduct' 
                    AND column_name = '__KEY'
                ), 'ALTER TABLE products_variantproduct DROP COLUMN `__KEY`', 'SELECT 1');
                PREPARE stmt FROM @query;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                """,
                
                """
                SET @query = IF(EXISTS(
                    SELECT * FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'products_variantproduct' 
                    AND column_name = 'UID'
                ), 'ALTER TABLE products_variantproduct DROP COLUMN `UID`', 'SELECT 1');
                PREPARE stmt FROM @query;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                """,
                
                """
                SET @query = IF(EXISTS(
                    SELECT * FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'products_variantproduct' 
                    AND column_name = 'legacy_uid'
                ), 'ALTER TABLE products_variantproduct DROP COLUMN `legacy_uid`', 'SELECT 1');
                PREPARE stmt FROM @query;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                """,
                
                """
                SET @query = IF(EXISTS(
                    SELECT * FROM information_schema.columns 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'products_parentproduct' 
                    AND column_name = 'legacy_uid'
                ), 'ALTER TABLE products_parentproduct DROP COLUMN `legacy_uid`', 'SELECT 1');
                PREPARE stmt FROM @query;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                """
            ],
            reverse_sql=[]
        ),
    ]
