# Generated by Django 5.1.6 on 2025-03-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variantproduct_legacy_familie'),
    ]

    operations = [
        migrations.RunSQL(
            # This is a no-op SQL operation that will be marked as applied
            # but won't try to rename any columns
            sql="SELECT 1;",
            reverse_sql="SELECT 1;",
        ),
    ] 