# Generated by Django 4.2.11 on 2025-02-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_explicit_db_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the sync process started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sync process completed', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', help_text='Current status of the sync process', max_length=20)),
                ('images_added', models.IntegerField(default=0, help_text='Number of new images added')),
                ('images_updated', models.IntegerField(default=0, help_text='Number of existing images updated')),
                ('images_deleted', models.IntegerField(default=0, help_text='Number of images deleted')),
                ('products_affected', models.IntegerField(default=0, help_text='Number of products affected by the sync')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the sync failed')),
            ],
            options={
                'verbose_name': 'Image Sync Log',
                'verbose_name_plural': 'Image Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID from external image database', max_length=255)),
                ('image_url', models.URLField(help_text='URL to the full-size image', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to the thumbnail image', max_length=500, null=True)),
                ('image_type', models.CharField(help_text='Type of image (e.g., "Produktfoto")', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the product')),
                ('is_front', models.BooleanField(default=False, help_text='Whether this image is marked as "front" in the source system')),
                ('priority', models.IntegerField(default=0, help_text='Display priority (lower numbers shown first)')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from the source system')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='When the image was last synced from the external system')),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variantproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['priority', 'id'],
                'unique_together': {('product', 'external_id')},
            },
        ),
    ]
