# Generated by Django 5.1.6 on 2025-03-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_variantproduct_legacy_familie'),
    ]

    operations = [
        migrations.RunSQL(
            # Force Django to recognize the field as already migrated
            sql="UPDATE django_content_type SET model = 'variantproduct' WHERE app_label = 'products' AND model = 'variantproduct';",
            reverse_sql="SELECT 1;",
        ),
    ] 