# Generated by Django 5.1.6 on 2025-02-28 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_imagesynclog_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the variant', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='Current inventory level'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in millimeters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Whether this is a bestselling variant'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this variant is featured'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Whether this is a new variant'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='last_ordered_date',
            field=models.DateField(blank=True, help_text='Date when this variant was last ordered', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='lead_time_days',
            field=models.IntegerField(blank=True, help_text='Lead time for replenishment in days', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in millimeters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='List/retail price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='material',
            field=models.CharField(blank=True, help_text='Material composition', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='max_stock_level',
            field=models.IntegerField(blank=True, help_text='Maximum stock level to maintain', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='min_stock_level',
            field=models.IntegerField(blank=True, help_text='Minimum stock level to maintain', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='reorder_point',
            field=models.IntegerField(blank=True, help_text='Point at which to reorder inventory', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the variant', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='units_sold_previous_year',
            field=models.IntegerField(default=0, help_text='Units sold in previous year'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='units_sold_year',
            field=models.IntegerField(default=0, help_text='Units sold in current year'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in millimeters', max_digits=10, null=True),
        ),
    ]
