# Generated by Django 5.1.6 on 2025-02-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_variantproduct_color_variantproduct_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='auslaufdatum',
            field=models.DateTimeField(blank=True, help_text='Discontinuation date (maps to Auslaufdatum in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='bezeichnung_fs',
            field=models.CharField(blank=True, help_text='Foreign language description (maps to Bezeichnung_FS in Artikel_Variante)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='is_verkaufsartikel',
            field=models.BooleanField(default=False, help_text='Whether this is a sales article (maps to Verkaufsartikel in Artikel_Variante)'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_created_date',
            field=models.DateTimeField(blank=True, help_text='Creation date in legacy system (maps to created_date in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_created_name',
            field=models.CharField(blank=True, help_text='Creator name in legacy system (maps to created_name in Artikel_Variante)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_modified_date',
            field=models.DateTimeField(blank=True, help_text='Modification date in legacy system (maps to modified_date in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_modified_name',
            field=models.CharField(blank=True, help_text='Modifier name in legacy system (maps to modified_name in Artikel_Variante)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_publish',
            field=models.JSONField(blank=True, default=dict, help_text='Publishing channels (maps to Publish in Artikel_Variante)'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_sales_channel',
            field=models.JSONField(blank=True, default=dict, help_text='Sales channels (maps to SalesChannel in Artikel_Variante)'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_tags',
            field=models.CharField(blank=True, help_text='Tags reference (maps to Tags_ in Artikel_Variante)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='legacy_typ',
            field=models.IntegerField(blank=True, help_text='Type value from legacy system (maps to Typ in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price (maps to Preise.Coll[Art="Einkauf"].Preis in Artikel_Variante)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended price (maps to Preise.Coll[Art="Empf."].Preis in Artikel_Variante)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Release date (maps to Release_Date in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retail price (maps to Preise.Coll[Art="Laden"].Preis in Artikel_Variante)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='retail_unit',
            field=models.IntegerField(blank=True, help_text='Retail packaging unit (maps to Preise.Coll[Art="Laden"].VE in Artikel_Variante)', null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='shopware_id',
            field=models.CharField(blank=True, help_text='Shopware ID (maps to shopware in Artikel_Variante)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='wholesale_unit',
            field=models.IntegerField(blank=True, help_text='Wholesale packaging unit (maps to Preise.Coll[Art="Handel"].VE in Artikel_Variante)', null=True),
        ),
    ]
