# Generated by Django 5.1.6 on 2025-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_variantproduct_auslaufdatum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='bezeichnung_fs',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_created_date',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_created_name',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_modified_date',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_modified_name',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_publish',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_sales_channel',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_tags',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='legacy_typ',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='recommended_price',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='shopware_id',
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price (maps to Preise.Coll[Art="Handel"].Preis in Artikel_Variante)', max_digits=10, null=True),
        ),
    ]
