# Generated by Django 5.1.6 on 2025-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_imagesynclog_id_and_more_squashed_0011_cleanup_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesynclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
