# Generated manually

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_imagesynclog_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_imagesynclog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            """,
            reverse_sql="""
            ALTER TABLE products_imagesynclog ALTER COLUMN id DROP IDENTITY IF EXISTS;
            """
        ),
    ] 