# Generated by Django 5.1.6 on 2025-03-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_variantproduct_bezeichnung_fs_and_more'),
        ('products', '0014_create_productimage_table'),
    ]

    operations = [
    ]
