# Generated by Django 5.1.6 on 2025-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_fix_variant_table'),
    ]

    operations = [
        # Run raw SQL to ensure columns are actually dropped from the database
        migrations.RunSQL(
            sql=[
                # PostgreSQL-compatible syntax for dropping columns if they exist
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = current_schema() 
                        AND table_name = 'products_variantproduct' 
                        AND column_name = '__key'
                    ) THEN
                        ALTER TABLE products_variantproduct DROP COLUMN "__key";
                    END IF;
                END $$;
                """,
                
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = current_schema() 
                        AND table_name = 'products_variantproduct' 
                        AND column_name = 'uid'
                    ) THEN
                        ALTER TABLE products_variantproduct DROP COLUMN "uid";
                    END IF;
                END $$;
                """,
                
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = current_schema() 
                        AND table_name = 'products_variantproduct' 
                        AND column_name = 'legacy_uid'
                    ) THEN
                        ALTER TABLE products_variantproduct DROP COLUMN "legacy_uid";
                    END IF;
                END $$;
                """,
                
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = current_schema() 
                        AND table_name = 'products_parentproduct' 
                        AND column_name = 'legacy_uid'
                    ) THEN
                        ALTER TABLE products_parentproduct DROP COLUMN "legacy_uid";
                    END IF;
                END $$;
                """
            ],
            reverse_sql=[]
        ),
    ]
