# Generated by Django 5.1.6 on 2025-03-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_set_status_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - split into separate statements
            [
                """
                -- Drop the unique constraint if it exists
                ALTER TABLE products_productimage DROP CONSTRAINT IF EXISTS products_productimage_product_id_external_id_key;
                """,
                """
                -- Make product field nullable
                ALTER TABLE products_productimage ALTER COLUMN product_id DROP NOT NULL;
                """,
                """
                -- Fix duplicate entries by setting product_id to NULL for duplicates
                WITH duplicates AS (
                    SELECT external_id, product_id, id,
                           ROW_NUMBER() OVER (PARTITION BY external_id, product_id ORDER BY id) as row_num
                    FROM products_productimage
                    WHERE external_id IS NOT NULL AND product_id IS NOT NULL
                )
                UPDATE products_productimage
                SET product_id = NULL
                WHERE id IN (
                    SELECT id FROM duplicates WHERE row_num > 1
                );
                """,
                """
                -- Add the conditional unique constraint
                CREATE UNIQUE INDEX unique_product_image ON products_productimage (product_id, external_id) WHERE product_id IS NOT NULL;
                """
            ],
            
            # Reverse SQL - split into separate statements
            [
                """
                -- Remove the conditional unique constraint
                DROP INDEX IF EXISTS unique_product_image;
                """,
                """
                -- Make product field required again
                UPDATE products_productimage SET product_id = (SELECT id FROM products_variantproduct LIMIT 1) WHERE product_id IS NULL;
                """,
                """
                ALTER TABLE products_productimage ALTER COLUMN product_id SET NOT NULL;
                """,
                """
                -- Add back the original unique constraint
                ALTER TABLE products_productimage ADD CONSTRAINT products_productimage_product_id_external_id_key UNIQUE (product_id, external_id);
                """
            ]
        ),
    ]
