# Generated by Django 5.1.7 on 2025-03-18 22:28

from django.db import migrations

def no_op(apps, schema_editor):
    # This migration is a no-op because the database already has the desired schema
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(no_op),
    ]
