# Generated by Django 5.1.7 on 2025-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dimensions",
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="parentproduct",
            name="dimensions",
            field=models.JSONField(null=True, blank=True),
        ),
    ]
