# Generated by Django 5.1.7 on 2025-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentproduct",
            name="is_new",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a new product (maps to Neu in Artikel_Familie)",
            ),
        ),
        migrations.AddField(
            model_name="parentproduct",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Release date (maps to Release_date in Artikel_Familie)",
                null=True,
            ),
        ),
    ]
