# Generated by Django 5.1.6 on 2025-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentproduct",
            name="base_sku",
            field=models.CharField(
                db_index=True, help_text="Base SKU for variants", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique category code",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(help_text="Category name", max_length=255),
        ),
    ]
