# Generated by Django 5.1.7 on 2025-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentproduct",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
