# Generated by Django 5.1.7 on 2025-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20250311_0044"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantproduct",
            name="legacy_artikel_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Legacy ID_Artikel_Stamm value from the Artikel_Stamm table",
                max_length=50,
                null=True,
            ),
        ),
    ]
