# Generated by Django 5.1.7 on 2025-03-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20250320_2148"),
    ]

    operations = [
        # We're not making any changes, just fixing a migration conflict
    ]
