# Generated by Django 5.1.7 on 2025-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_parentproduct_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentproduct",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
