# Generated by Django 5.1.7 on 2025-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_parentproduct_is_new_parentproduct_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantproduct",
            name="is_verkaufsartikel",
            field=models.SmallIntegerField(
                default=0,
                help_text="Whether this is a sales article (maps to Verkaufsartikel in Artikel_Variante). 1 for True, 0 for False.",
            ),
        ),
    ]
