# Generated by Django 5.1.7 on 2025-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_parentproduct_base_sku_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentproduct",
            name="height_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in millimeters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parentproduct",
            name="length_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in millimeters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parentproduct",
            name="width_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in millimeters",
                max_digits=10,
                null=True,
            ),
        ),
    ]
