# Generated by Django 4.2.20 on 2025-03-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_parentproduct_base_sku_and_more"),
        ("products", "0002_remove_parentproduct_is_placeholder"),
    ]

    operations = []
