# Generated by Django 5.1.7 on 2025-03-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20250320_2156"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Drop index on slug field if it exists
            DROP INDEX IF EXISTS products_parentproduct_slug_2f36ca27_like;
            
            -- Drop any unique constraint on slug field
            ALTER TABLE products_parentproduct DROP CONSTRAINT IF EXISTS products_parentproduct_slug_key;
            
            -- Check if slug column exists and drop it if it does
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='products_parentproduct' AND column_name='slug'
                )
                THEN
                    ALTER TABLE products_parentproduct DROP COLUMN slug;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- This migration cannot be reversed since the slug field is being removed
            """
        ),
    ]
