# Generated by Django 5.1.7 on 2025-03-18 23:14

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0003_remove_parentproduct_base_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly tag name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tag description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the object')),
                ('field_name', models.CharField(help_text='Name of the field being overridden', max_length=100)),
                ('inherit', models.BooleanField(default=True, help_text='Whether to inherit the field value from parent')),
                ('content_type', models.ForeignKey(help_text='Content type of the model containing the field', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Field Override',
                'verbose_name_plural': 'Field Overrides',
                'unique_together': {('content_type', 'object_id', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='M2MOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the object')),
                ('relationship_name', models.CharField(help_text='Name of the M2M relationship being overridden', max_length=100)),
                ('inherit', models.BooleanField(default=True, help_text='Whether to inherit relationships from parent')),
                ('content_type', models.ForeignKey(help_text='Content type of the model containing the M2M relationship', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'M2M Override',
                'verbose_name_plural': 'M2M Overrides',
                'unique_together': {('content_type', 'object_id', 'relationship_name')},
            },
        ),
    ]
