# Generated by Django 5.1.7 on 2025-03-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_parentproduct_id"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop the existing sequence if it exists
            DROP SEQUENCE IF EXISTS products_parentproduct_id_seq CASCADE;
            
            -- Create a new sequence
            CREATE SEQUENCE products_parentproduct_id_seq;
            
            -- Set the sequence to be owned by the id column
            ALTER SEQUENCE products_parentproduct_id_seq 
            OWNED BY products_parentproduct.id;
            
            -- Set the default value for the id column to use the sequence
            ALTER TABLE products_parentproduct 
            ALTER COLUMN id SET DEFAULT 
            nextval('products_parentproduct_id_seq');
            
            -- Set the sequence to start from the maximum id value + 1
            SELECT setval(
                'products_parentproduct_id_seq', 
                COALESCE((SELECT MAX(id) FROM products_parentproduct), 0) + 1, 
                false
            );
            """,
            reverse_sql="""
            -- No reverse operation needed
            """
        ),
    ]
