# Generated by Django 5.1.7 on 2025-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variantproduct_is_verkaufsartikel'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE products_variantproduct ALTER COLUMN is_verkaufsartikel TYPE boolean USING CASE WHEN is_verkaufsartikel = 1 THEN true ELSE false END;',
            reverse_sql='ALTER TABLE products_variantproduct ALTER COLUMN is_verkaufsartikel TYPE smallint USING CASE WHEN is_verkaufsartikel THEN 1 ELSE 0 END;',
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='is_verkaufsartikel',
            field=models.BooleanField(
                db_column='is_verkaufsartikel',
                default=False,
                help_text='Whether this is a sales article (maps to Verkaufsartikel in Artikel_Variante)',
            ),
        ),
    ]
