# Generated by Django 5.0.6 on 2025-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250320_2156'),
        # Add dependency on the core migration that creates TaggedItem, if needed later
        # ('core', '0002_tag_taggeditem'), 
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="Tag",
        # ), # Commented out: Postpone deletion until after data migration and GenericRelation setup
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="parentproduct",
                    name="tags",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Tags assigned to this parent product",
                        related_name="parent_products",
                        to="core.tag",
                    ),
                ),
            ],
            database_operations=[], # No database change needed for this state update
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="variantproduct",
                    name="tags",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Tags assigned directly to this variant product",
                        related_name="variant_products",
                        to="core.tag", # Updated to point to core.Tag temporarily during transition
                    ),
                ),
            ],
            database_operations=[], # No database change needed for this state update
        ),
    ]
