# Generated by Django 5.1.7 on 2025-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_variantproduct_legacy_artikel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantproduct",
            name="parent",
            field=models.ForeignKey(
                db_constraint=True,  # Explicitly set to create a DB constraint
                help_text=(
                    "Parent product - maps to Familie_ field in "
                    "Artikel_Variante which references "
                    "__KEY in Artikel_Familie"
                ),
                null=True,
                on_delete=models.CASCADE,
                related_name="variants",
                to="products.parentproduct",
            ),
        ),
    ]
