# Generated by Django 5.1.7 on 2025-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_tag_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned to this parent product', related_name='parent_products', to='products.tag'),
        ),
        migrations.AddField(
            model_name='variantproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned directly to this variant product', related_name='variant_products', to='products.tag'),
        ),
    ]
