# Generated by Django 5.1.7 on 2025-03-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_variant_product_fk_constraint"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_variantproduct 
            ADD CONSTRAINT fk_variantproduct_parent 
            FOREIGN KEY (parent_id) 
            REFERENCES products_parentproduct(id) 
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE products_variantproduct 
            DROP CONSTRAINT IF EXISTS fk_variantproduct_parent;
            """,
        ),
    ]
