# Generated by Django 5.1.7 on 2025-03-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_delete_tag_alter_parentproduct_tags_and_more"),
        ("core", "0003_populate_tagged_items"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.RemoveField(
            model_name="parentproduct",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="variantproduct",
            name="tags",
        ),
    ]
