# Generated by Django 5.1.7 on 2025-03-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20250314_0007"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentproduct",
            name="is_placeholder",
        ),
    ] 