# Generated by Django 5.1.8 on 2025-04-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_supplier"),
        ("products", "0005_delete_tag_remove_parentproduct_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentproduct",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link to the primary supplier of this product.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="business.supplier",
                verbose_name="Supplier",
            ),
        ),
    ]
