# Generated by Django 5.1.6 on 2025-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_variantproduct_is_bestseller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantproduct",
            name="is_bestseller",
            field=models.BooleanField(
                default=False, help_text="Whether this is a bestselling variant"
            ),
        ),
        migrations.AlterField(
            model_name="variantproduct",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Whether this variant is featured"
            ),
        ),
        migrations.AlterField(
            model_name="variantproduct",
            name="is_new",
            field=models.BooleanField(
                default=False, help_text="Whether this is a new variant"
            ),
        ),
    ]
