# Generated by Django 5.1.7 on 2025-03-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_number",
            field=models.CharField(
                blank=True,
                help_text="Address number from legacy system",
                max_length=50,
                null=True,
            ),
        ),
    ]
