# Generated by Django 5.1.6 on 2025-03-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = []
