# Generated by Django 5.1.8 on 2025-04-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Delivery"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("FULLY_DELIVERED", "Fully Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Overall delivery status based on line items",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="SalesRecordRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the legacy system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "legacy_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp in legacy system",
                        null=True,
                    ),
                ),
                (
                    "is_synchronized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record is synchronized with the legacy system",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("RELATES_TO", "Relates To"),
                            ("SPLIT_FROM", "Split From"),
                            ("RETURN_OF", "Return Of"),
                            ("CREDITS", "Credits"),
                            ("REFERENCES", "References"),
                        ],
                        db_index=True,
                        default="RELATES_TO",
                        help_text="The type of relationship between the records.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the relationship."
                    ),
                ),
                (
                    "from_record",
                    models.ForeignKey(
                        help_text="The source record in the relationship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="sales.salesrecord",
                    ),
                ),
                (
                    "to_record",
                    models.ForeignKey(
                        help_text="The target record in the relationship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="sales.salesrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Record Relationship",
                "verbose_name_plural": "Sales Record Relationships",
                "ordering": ["from_record", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_record"], name="sales_sales_from_re_9d3481_idx"
                    ),
                    models.Index(
                        fields=["to_record"], name="sales_sales_to_reco_b0a92b_idx"
                    ),
                    models.Index(
                        fields=["relationship_type"],
                        name="sales_sales_relatio_4e8438_idx",
                    ),
                ],
                "unique_together": {("from_record", "to_record", "relationship_type")},
            },
        ),
    ]
