# Generated by Django 5.1.7 on 2025-03-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_paymentmethod_paymentterms_shippingmethod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Billing address (maps to Rech_Adr in legacy system)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_records",
                to="sales.address",
            ),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Shipping address (maps to Lief_Adr in legacy system)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_records",
                to="sales.address",
            ),
        ),
    ]
