# Generated by Django 5.1.8 on 2025-04-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_salesrecord_delivery_status_salesrecordrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="amount_paid_external",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Amount reported as paid by the external system (e.g., BuchhaltungsButler)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
