# Generated by Django 5.1.7 on 2025-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_salesrecord_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(
                blank=True, help_text="Customer name", max_length=200
            ),
        ),
    ]
