# Generated by Django 5.1.6 on 2025-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntityMappingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity being mapped (e.g., product, customer)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "legacy_table",
                    models.CharField(
                        help_text="Name of the table in the legacy system",
                        max_length=100,
                    ),
                ),
                (
                    "new_model",
                    models.CharField(
                        help_text="Full path to the model class in the new system (e.g., pyerp.products.models.Product)",
                        max_length=100,
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        help_text="JSON mapping of legacy fields to new fields, including transformations"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this mapping configuration is active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this mapping configuration was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this mapping configuration was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Mapping Configuration",
                "verbose_name_plural": "Entity Mapping Configurations",
                "ordering": ["entity_type"],
            },
        ),
        migrations.CreateModel(
            name="TransformationFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the transformation function",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what the transformation function does",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        help_text="Python code for the transformation function. Should take a single value parameter and return the transformed value."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this transformation function is active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this transformation function was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this transformation function was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transformation Function",
                "verbose_name_plural": "Transformation Functions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EntityMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity being mapped (e.g., product, customer)",
                        max_length=50,
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        help_text="ID of the entity in the legacy system",
                        max_length=100,
                    ),
                ),
                (
                    "new_id",
                    models.CharField(
                        help_text="ID of the entity in the new system", max_length=100
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the entity was last synchronized"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Mapping",
                "verbose_name_plural": "Entity Mappings",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "legacy_id"],
                        name="legacy_sync_entity__f1940a_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "new_id"],
                        name="legacy_sync_entity__72c4be_idx",
                    ),
                ],
                "unique_together": {
                    ("entity_type", "legacy_id"),
                    ("entity_type", "new_id"),
                },
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity being synchronized (e.g., product, customer)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partially_completed", "Partially Completed"),
                        ],
                        default="pending",
                        help_text="Current status of the synchronization operation",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the synchronization operation started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the synchronization operation completed",
                        null=True,
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of records processed during synchronization",
                    ),
                ),
                (
                    "records_created",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of new records created during synchronization",
                    ),
                ),
                (
                    "records_updated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of existing records updated during synchronization",
                    ),
                ),
                (
                    "records_failed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of records that failed to synchronize",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the synchronization operation failed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronization Log",
                "verbose_name_plural": "Synchronization Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type"], name="legacy_sync_entity__93f97b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="legacy_sync_status_dadb42_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="legacy_sync_started_d77697_idx"
                    ),
                ],
            },
        ),
    ]
