# Generated by Django 4.2.11 on 2025-02-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entitymapping',
            new_name='legacy_sync_entity__f1940a_idx',
            old_name='legacy_sync_entity_t_1a9d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='entitymapping',
            new_name='legacy_sync_entity__72c4be_idx',
            old_name='legacy_sync_entity_t_e7a5d9_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='legacy_sync_entity__93f97b_idx',
            old_name='legacy_sync_entity_t_e8701c_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='legacy_sync_status_dadb42_idx',
            old_name='legacy_sync_status_0e6ed4_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='legacy_sync_started_d77697_idx',
            old_name='legacy_sync_started_1a5d34_idx',
        ),
    ]
