# Generated by Django 5.1.7 on 2025-03-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Production order identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="Order Number",
                    ),
                ),
                (
                    "form_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference to manufacturing form/template",
                        max_length=50,
                        verbose_name="Form Number",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Total production quantity",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "planned_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planned Date"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Production priority (higher values indicate higher priority)",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID from legacy system",
                        max_length=100,
                        verbose_name="Legacy ID",
                    ),
                ),
                (
                    "legacy_key",
                    models.CharField(
                        blank=True,
                        help_text="__KEY from legacy system",
                        max_length=100,
                        verbose_name="Legacy Key",
                    ),
                ),
                (
                    "legacy_form_id",
                    models.CharField(
                        blank=True,
                        help_text="Form reference from legacy system",
                        max_length=100,
                        verbose_name="Legacy Form ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_production_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "ordering": ["-creation_date", "order_number"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("E", "Assembly"),
                            ("G", "Manufacturing"),
                            ("P", "Packaging"),
                            ("Q", "Quality Control"),
                            ("T", "Testing"),
                        ],
                        max_length=10,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "item_number",
                    models.IntegerField(
                        help_text="Sequential number within the production order",
                        verbose_name="Item Number",
                    ),
                ),
                (
                    "target_quantity",
                    models.IntegerField(default=0, verbose_name="Target Quantity"),
                ),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="Completed Quantity"),
                ),
                (
                    "remaining_quantity",
                    models.IntegerField(default=0, verbose_name="Remaining Quantity"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Product SKU"
                    ),
                ),
                (
                    "product_share",
                    models.FloatField(
                        default=1.0,
                        help_text="Proportion of the product used in this operation",
                        verbose_name="Product Share",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated time in seconds",
                        verbose_name="Estimated Time",
                    ),
                ),
                (
                    "standard_time",
                    models.FloatField(
                        default=0,
                        help_text="Standard time per unit",
                        verbose_name="Standard Time",
                    ),
                ),
                ("value", models.FloatField(default=0, verbose_name="Value")),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID from legacy system",
                        max_length=100,
                        verbose_name="Legacy ID",
                    ),
                ),
                (
                    "legacy_key",
                    models.CharField(
                        blank=True,
                        help_text="__KEY from legacy system",
                        max_length=100,
                        verbose_name="Legacy Key",
                    ),
                ),
                (
                    "legacy_kostenstelle_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Legacy Cost Center ID"
                    ),
                ),
                (
                    "legacy_form_artikel_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Legacy Form Article ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.productionorder",
                        verbose_name="Production Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order Item",
                "verbose_name_plural": "Production Order Items",
                "ordering": ["production_order", "item_number"],
                "unique_together": {("production_order", "item_number")},
            },
        ),
    ]
