# Generated by Django 5.1.7 on 2025-03-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorderitem",
            name="operation_type",
            field=models.CharField(
                help_text="Production step type code from legacy system",
                max_length=10,
                verbose_name="Operation Type",
            ),
        ),
    ]
