# Generated by Django 5.1.7 on 2025-03-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_initial"),
        ("products", "0003_auto_20250320_2156"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_uuid",
                    models.CharField(
                        db_index=True,
                        help_text="UUID (__KEY) from the legacy 'Formen' table",
                        max_length=36,
                        unique=True,
                        verbose_name="Legacy UUID",
                    ),
                ),
                (
                    "legacy_form_nr",
                    models.CharField(
                        db_index=True,
                        help_text="Form Number (FormNr) from the legacy 'Formen' table",
                        max_length=50,
                        verbose_name="Legacy Form Number",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description (Bezeichnung) from the legacy 'Formen' table",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Storage location (Lagerort) from the legacy 'Formen' table",
                        max_length=100,
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the mold is currently active (approximated, might need adjustment based on legacy 'Sperre')",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes (Bemerkung) from the legacy 'Formen' table",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "legacy_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp (__TIMESTAMP) from the legacy 'Formen' table",
                        null=True,
                        verbose_name="Legacy Timestamp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mold",
                "verbose_name_plural": "Molds",
                "ordering": ["legacy_form_nr"],
            },
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_production_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.CreateModel(
            name="MoldProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_uuid",
                    models.CharField(
                        db_index=True,
                        help_text="UUID (__KEY) from the legacy 'Form_Artikel' table",
                        max_length=36,
                        unique=True,
                        verbose_name="Legacy UUID",
                    ),
                ),
                (
                    "products_per_mold",
                    models.IntegerField(
                        default=1,
                        help_text="Number of products produced per mold cycle (Anzahl from Form_Artikel)",
                        verbose_name="Products per Mold",
                    ),
                ),
                (
                    "weight_per_product",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight of a single product produced by this mold (Gewichtung from Form_Artikel)",
                        max_digits=10,
                        null=True,
                        verbose_name="Weight per Product",
                    ),
                ),
                (
                    "legacy_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp (__TIMESTAMP) from the legacy 'Form_Artikel' table",
                        null=True,
                        verbose_name="Legacy Timestamp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mold",
                    models.ForeignKey(
                        help_text="The mold used to produce this product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="production.mold",
                        verbose_name="Mold",
                    ),
                ),
                (
                    "parent_product",
                    models.ForeignKey(
                        help_text="The product produced by this mold relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molds",
                        to="products.parentproduct",
                        verbose_name="Parent Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mold Product",
                "verbose_name_plural": "Mold Products",
                "ordering": ["mold", "parent_product"],
                "unique_together": {("mold", "parent_product")},
            },
        ),
    ]
