# Generated by Django 5.1.7 on 2025-03-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_productionorderitem_operation_type"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorderitem",
            name="parent_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to parent product (maps to Art_Nr in WerksauftrPos)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_items",
                to="products.parentproduct",
                verbose_name="Parent Product",
            ),
        ),
    ]
