# Generated by Django 5.1.7 on 2025-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_mold_alter_productionorder_created_by_moldproduct"),
        ("products", "0005_delete_tag_remove_parentproduct_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mold",
            name="alloys",
            field=models.ManyToManyField(
                blank=True,
                help_text="The alloy materials used in this mold",
                related_name="molds_using_alloy",
                to="products.parentproduct",
                verbose_name="Alloys",
            ),
        ),
    ]
