# Generated by Django 5.1.7 on 2025-03-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('production', '0003_productionorderitem_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorderitem',
            name='parent_product',
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='parent_product',
            field=models.ForeignKey(
                blank=True,
                help_text='Reference to parent product (maps to Art_Nr in WerksauftrPos)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='production_items',
                to='products.parentproduct',
                verbose_name='Parent Product'
            ),
        ),
    ]
