# Configuration for the standalone monitoring system
# This file defines the monitoring services separate from the main pyERP application

version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: pyerp-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - pyerp-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: pyerp-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - pyerp-network

volumes:
  elasticsearch_data:

networks:
  pyerp-network:
    external: true