# WARNING: NEVER ADD CREDENTIALS DIRECTLY TO THIS FILE
# All sensitive information should be stored in the environment files in config/env directory
# This file should be safe to commit to version control

version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8050:8050"
      - "6379:6379"
      - "3000:3000"  # Vue.js development server
    volumes:
      - ..:/app  # Mount local code directory to /app for hot reloading
      - pyerp_data:/app/data
    env_file:
      - ../config/env/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.development
      - REDIS_URL=redis://localhost:6379/0
      - DJANGO_DEBUG=True
      - PYTHONPATH=/app
      # Use the correct PostgreSQL server IP
      - DB_HOST=192.168.73.65
      - DB_PORT=5432
      - DB_NAME=pyerp_testing
      - DB_USER=postgres
    command: >
      bash -c "
        cd /app &&
        service redis-server start &&
        mkdir -p staticfiles &&
        mkdir -p static/images &&
        mkdir -p staticfiles/images &&
        # Copy frontend assets to static directories
        if [ -d /app/frontend/src/assets ]; then
          cp -r /app/frontend/src/assets/* /app/static/images/ || true
          cp -r /app/frontend/src/assets/* /app/staticfiles/images/ || true
        fi &&
        # Run the static assets copy script if it exists
        if [ -f /app/scripts/copy_static_assets.js ]; then
          node /app/scripts/copy_static_assets.js || true
        fi &&
        python manage.py collectstatic --noinput &&
        cd /app/frontend && npm run dev &
        cd /app && python manage.py runserver 0.0.0.0:8050
      "

volumes:
  pyerp_data: 