# WARNING: NEVER ADD CREDENTIALS DIRECTLY TO THIS FILE
# All sensitive information should be stored in the docker.env.dev file or environment variables
# This file should be safe to commit to version control

version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8050:8050"
      - "6379:6379"
      - "3000:3000"  # Vue.js development server
    volumes:
      - ..:/app  # Mount local code directory to /app for hot reloading
      - pyerp_data:/app/data
    env_file:
      - docker.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.development
      - REDIS_URL=redis://localhost:6379/0
      - DJANGO_DEBUG=True
      - PYTHONPATH=/app
      # External PostgreSQL connection details - actual credentials are in docker.env.dev
      - DB_HOST=192.168.73.65
      - DB_PORT=5432
      - DB_NAME=pyerp_testing
      - DB_USER=postgres
    command: >
      bash -c "
        cd /app &&
        service redis-server start &&
        mkdir -p staticfiles &&
        python manage.py collectstatic --noinput &&
        cd /app/frontend && npm run dev &
        cd /app && python manage.py runserver 0.0.0.0:8050
      "

volumes:
  pyerp_data: 