version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
      - "6379:6379"  # Redis port
    volumes:
      - pyerp_data:/app/data
      - ..:/app
    env_file:
      - ../.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.development
      - REDIS_URL=redis://localhost:6379/0
      - DJANGO_DEBUG=True
      - SECRET_KEY=development_secret_key
      - PYTHONPATH=/app
      # PostgreSQL connection settings
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-pyerp}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    restart: unless-stopped
    entrypoint: []
    command: >
      bash -c "
        redis-server --daemonize yes &&
        cd /app &&
        python -m pip install python-dotenv dj-database-url django-debug-toolbar whitenoise &&
        echo 'Starting Django development server...' &&
        PYTHONPATH=/app python -m django runserver 0.0.0.0:8000
      "

volumes:
  pyerp_data: 