# WARNING: NEVER ADD CREDENTIALS DIRECTLY TO THIS FILE
# All sensitive information should be stored in the environment files in config/env directory
# This file should be safe to commit to version control

version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: pyerp-dev
    ports:
      - "8050:8050"
      - "3000:3000"  # Vue.js development server
    volumes:
      - ..:/app  # Mount local code directory to /app for hot reloading
      - pyerp_data:/app/data
    env_file:
      - ../config/env/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.config.settings.development
      - REDIS_URL=redis://127.0.0.1:6379/0
      - DJANGO_DEBUG=True
      - PYTHONPATH=/app
      # Use the correct PostgreSQL server IP
      - DB_HOST=192.168.73.65
      - DB_PORT=5432
      - DB_NAME=pyerp_testing
      - DB_USER=postgres
    command: >
      bash -c "
        cd /app &&
        # Ensure Redis data directory exists and has correct permissions
        mkdir -p /var/lib/redis &&
        chown redis:redis /var/lib/redis &&
        chmod 750 /var/lib/redis &&
        # Run the static directories setup script
        bash /app/docker/ensure_static_dirs.sh &&
        # Start supervisord
        /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
      "

volumes:
  pyerp_data:
