# WARNING: NEVER ADD CREDENTIALS DIRECTLY TO THIS FILE
# All sensitive information should be stored in the docker.env.dev file or environment variables
# This file should be safe to commit to version control

version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8050:8050"
      - "6379:6379"
    volumes:
      - pyerp_data:/app/data
    env_file:
      - docker.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.development
      - REDIS_URL=redis://localhost:6379/0
      - DJANGO_DEBUG=True
      - PYTHONPATH=/app
      # External PostgreSQL connection details - actual credentials are in docker.env.dev
      - DB_HOST=192.168.73.65
      - DB_PORT=5432
      - DB_NAME=pyerp_testing
      - DB_USER=postgres
    command: >
      bash -c "
        cd /app &&
        service redis-server start &&
        export PGPASSWORD=$DB_PASSWORD &&
        psql -h $DB_HOST -U $DB_USER -p $DB_PORT -c \"DROP DATABASE IF EXISTS $DB_NAME\" &&
        psql -h $DB_HOST -U $DB_USER -p $DB_PORT -c \"CREATE DATABASE $DB_NAME\" &&
        python manage.py migrate contenttypes &&
        python manage.py migrate auth &&
        python manage.py migrate admin &&
        python manage.py migrate django_celery_beat &&
        python manage.py migrate django_celery_results &&
        python manage.py migrate legacy_sync &&
        python manage.py migrate monitoring &&
        python manage.py migrate products 0007_remove_redundant_legacy_fields --fake &&
        python manage.py migrate core &&
        python manage.py migrate sessions &&
        python manage.py runserver 0.0.0.0:8050
      "

volumes:
  pyerp_data: 