# Configuration for the monitoring system
# This file defines the monitoring service with Elasticsearch and Kibana in the same container

services:
  elastic-kibana:
    build:
      context: ..
      dockerfile: docker/Dockerfile.elastic-kibana
    container_name: pyerp-elastic-kibana
    platform: linux/arm64
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5602:5601"
    volumes:
      - es_kibana_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.system_call_filter=false
      - "ES_ENV_ELASTICSEARCH.HOSTS=http://localhost:9200"
      - "ES_ENV_SERVER.HOST=0.0.0.0"
    networks:
      - pyerp-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

volumes:
  es_kibana_data:
    driver: local

networks:
  pyerp-network:
    external: true