version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: pyerp
    ports:
      - "8050:8050"
      - "80:80"
    env_file:
      - ../config/env/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.production
      - REDIS_URL=redis://localhost:6379/0
      # External PostgreSQL connection details
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-pyerp_testing}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - pyerp_data:/app
    healthcheck:
      test: curl --fail http://localhost:8050/admin/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pyerp_data: