version: "3.8"

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: pyerp-prod
    restart: always
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443" # Add explicit HTTPS port
      - "9201:9200" # Elasticsearch - Changed port to avoid conflict
      - "5602:5601" # Kibana - Changed port to avoid conflict
    env_file:
      - ../config/env/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.config.settings.production
      - REDIS_URL=redis://localhost:6379/0
      # ELK stack configuration
      - ELASTICSEARCH_HOST=localhost
      - ELASTICSEARCH_PORT=9200
      - KIBANA_HOST=localhost
      - KIBANA_PORT=5601
    volumes:
      - pyerp_data:/app
      - es_data:/var/lib/elasticsearch
    networks:
      - default
    dns_search: .
    healthcheck:
      test: curl --fail http://localhost:8000/admin/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      bash -c "
        cd /app &&
        # Run the static directories setup script
        bash /app/docker/ensure_static_dirs.sh &&
        # Start supervisord
        /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
      "

  zebra-day:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zebra_day
    container_name: zebra-day-prod
    restart: always
    # No ports exposed externally by default in prod, only accessible within the docker network
    # environment:
      # Optional: Override startup options if needed
      # - ZDAY_START_OPTS=""
    networks:
      - default # Connect to the default bridge network for communication with pyerp
    volumes:
      - zebra_day_etc:/usr/local/lib/python3.10/site-packages/zebra_day/etc

volumes:
  pyerp_data:
  es_data:
  zebra_day_etc: {}

networks:
  default:
    driver: bridge
  # supabase_default:
  #   external: true
