# Configuration for the standalone monitoring system
# This file defines the monitoring services separate from the main pyERP application

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: pyerp-elasticsearch
    platform: linux/arm64
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.system_call_filter=false
    networks:
      - pyerp-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: kibana:7.17.0
    container_name: pyerp-monitoring
    platform: linux/arm64
    ports:
      - "5602:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://pyerp-elasticsearch:9200
    networks:
      - pyerp-network
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local

networks:
  pyerp-network:
    external: true