version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8050:8050"
    volumes:
      - pyerp_data:/app/data
    env_file:
      - docker.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.development
      - REDIS_URL=redis://localhost:6379/0
      - DJANGO_DEBUG=True
      - PYTHONPATH=/app
      # External PostgreSQL connection details
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-pyerp_dev}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    command: >
      bash -c "
        cd /app &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8050
      "

volumes:
  pyerp_data: 