version: '3.8'

services:
  pyerp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: pyerp_all_in_one
    ports:
      - "8080:80"
      - "8443:443"
      - "8051:8050"
    env_file:
      - ../.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=pyerp.settings.production
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-pyerp_testing}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - REDIS_URL=redis://localhost:6379/0
      - RUN_CELERY=true
      - RUN_CELERY_BEAT=true
      - RUN_NGINX=true
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - redis_data_prod:/data
      - static_volume:/app/static
      - media_volume:/app/media
      - log_volume:/app/logs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot    # For Certbot verification
      - ./certbot/conf:/etc/letsencrypt   # For storing certificates
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8050/admin/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data_prod:
  redis_data_prod:
  static_volume:
  media_volume:
  log_volume: