# Generated by Django 5.1.7 on 2025-03-28 18:56

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_tag_taggeditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee Number"
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from the legacy system",
                        max_length=50,
                        null=True,
                        verbose_name="Legacy ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mobile Phone",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="Hire Date"),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termination Date"
                    ),
                ),
                (
                    "is_terminated",
                    models.BooleanField(default=False, verbose_name="Is Terminated"),
                ),
                (
                    "is_present",
                    models.BooleanField(default=True, verbose_name="Is Present"),
                ),
                (
                    "weekly_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Weekly Hours",
                    ),
                ),
                (
                    "daily_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Daily Hours",
                    ),
                ),
                (
                    "salary_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Salary Code"
                    ),
                ),
                (
                    "annual_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Annual Salary",
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monthly Salary",
                    ),
                ),
                (
                    "annual_vacation_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Annual Vacation Days"
                    ),
                ),
                (
                    "ad_username",
                    models.CharField(
                        blank=True,
                        help_text="Active Directory username",
                        max_length=100,
                        null=True,
                        verbose_name="AD Username",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
