# Generated by Django 5.1.8 on 2025-04-11 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_employee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Supplier ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Supplier Name"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact Person"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Tax ID"),
                ),
                (
                    "accounting_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the external accounting system, if applicable",
                        max_length=100,
                        null=True,
                        verbose_name="Accounting System ID",
                    ),
                ),
                (
                    "creditor_id",
                    models.CharField(
                        blank=True,
                        help_text="Creditor ID for Document Management Systems (e.g., Paperless)",
                        max_length=100,
                        null=True,
                        verbose_name="Creditor ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful sync with external systems",
                        null=True,
                        verbose_name="Last Synced At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
    ]
