# Generated by Django 5.1.8 on 2025-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Contact Person"
            ),
        ),
    ]
