# Generated by Django 5.1.8 on 2025-04-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_alter_supplier_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
