# Generated by Django 5.1.8 on 2025-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_alter_supplier_address_alter_supplier_tax_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.AddField(
            model_name="supplier",
            name="additional_addressline",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Additional Address Line",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Zip Code"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone"
            ),
        ),
    ]
