# Generated by Django 5.1.7 on 2025-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_populate_tagged_items"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tag",
            table=None,
        ),
    ]
