# Generated by Django 5.1.7 on 2025-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_tag_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="active_layout_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the currently active dashboard layout",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="dashboard_layouts",
            field=models.JSONField(
                default=dict,
                help_text="JSON configuration of user's saved dashboard layouts",
            ),
        ),
    ]
