# Generated by Django 5.1.7 on 2025-04-07 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userpreference_active_layout_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the notification.", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The main content/body of the notification.",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_index=True,
                        default="system",
                        help_text="Category of the notification (e.g., 'system', 'user_message', 'task_update').",
                        max_length=50,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if the user has read the notification.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the notification was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the notification was last updated.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who will receive the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="core_notifi_user_id_f286cd_idx",
                    ),
                    models.Index(
                        fields=["user", "type", "is_read", "-created_at"],
                        name="core_notifi_user_id_63d637_idx",
                    ),
                ],
            },
        ),
    ]
