# Generated by Django 5.1.8 on 2025-04-11 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Function to populate the new UUID field
def gen_uuid(apps, schema_editor):
    Notification = apps.get_model('core', 'Notification')
    for row in Notification.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_notification_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_completed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates if the to-do item has been completed (only applies to 'todo' type).",
                null=True,
                verbose_name="Is Completed (for To-Do)",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                help_text="Priority level for the to-do item (only applies to 'todo' type).",
                max_length=10,
                null=True,
                verbose_name="Priority (for To-Do)",
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                null=True,  # Temporarily allow null
                editable=False
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True, # Make unique before removing old PK
                null=False, # Make non-nullable
                editable=False
            ),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id', # Remove the old BigAutoField
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='uuid',
            new_name='id', # Rename the new UUID field to 'id'
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True, # Set as primary key
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="The main content/body of the notification.",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when the notification was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if the user has read the notification.",
                verbose_name="Is Read",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who sent the notification (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender User (if applicable)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(
                help_text="The title of the notification.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("direct_message", "Direct Message"),
                    ("todo", "To-Do"),
                ],
                db_index=True,
                default="system",
                help_text="Category of the notification (e.g., 'system', 'direct_message', 'todo').",
                max_length=20,
                verbose_name="Notification Type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the notification was last updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="The user who will receive the notification.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient User",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "type", "is_completed", "priority"],
                name="core_notifi_user_id_538db0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="core_notifi_created_d0c445_idx"
            ),
        ),
    ]
