# Generated by Django 5.1.7 on 2025-03-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_succeeded", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("is_full_sync", models.BooleanField(default=False)),
                ("sync_params", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("trace", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("mapping_config", models.JSONField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncLogDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True)),
                ("record_data", models.JSONField(default=dict)),
                (
                    "sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="sync.synclog",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="synclog",
            name="mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sync.syncmapping"
            ),
        ),
        migrations.AddField(
            model_name="syncmapping",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sync.syncsource"
            ),
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_sync_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_sync_id", models.CharField(blank=True, max_length=100)),
                ("last_successful_id", models.CharField(blank=True, max_length=100)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sync.syncmapping",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="syncmapping",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sync.synctarget"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncmapping",
            unique_together={("source", "target", "entity_type")},
        ),
    ]
