# Generated by Django 5.1.7 on 2025-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclogdetail",
            name="record_id",
            field=models.CharField(max_length=255),
        ),
    ]
