# Generated by Django 5.1.7 on 2025-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_rename_end_time_synclog_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
