# Generated by Django 5.1.7 on 2025-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_alter_synclog_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="synclog",
            table="audit_synclog",
        ),
    ]
