name: Build

on:
  push:
    branches: [ prod, dev,dev-ui ]
  pull_request:
    branches: [ prod, dev,dev-ui ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build pyERP Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.prod
          push: false
          tags: pyerp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/pyerp.tar
      
      - name: Upload pyERP Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyerp
          path: /tmp/pyerp.tar
          retention-days: 1
