name: Dependency Security Scan

on:
  schedule:
    - cron: '0 8 * * 1'  # Run every Monday at 8:00 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Scan for vulnerabilities
      run: |
        python scripts/security_scan.py
        
    - name: Create issue if vulnerabilities found
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security vulnerabilities found in dependencies',
            body: 'The dependency security scan has detected vulnerabilities. Please review the workflow run for details.'
          }) 