name: Linting

on:
  workflow_call:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop
      - prod
      - dev
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --force-reinstall flake8==7.0.0 mypy==1.5.1
          
          if [ -f requirements/requirements.dev.txt ]; then
            python -m pip install -r requirements/requirements.dev.txt
          fi
          
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          fi
          
          if [ -f requirements/requirements.prod.txt ]; then
            python -m pip install -r requirements/requirements.prod.txt
          fi

      - name: Lint with flake8
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check types with mypy
        run: python -m mypy .