name: Test Suite

on:
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group: [ui, backend, core, unit]
      fail-fast: false

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pyerp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.dev.txt

      - name: Set up Node.js
        if: matrix.test-group == 'ui'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend-react/package-lock.json'

      - name: Install React dependencies
        if: matrix.test-group == 'ui'
        working-directory: frontend-react
        run: npm ci

      - name: Run React UI tests
        if: matrix.test-group == 'ui'
        working-directory: frontend-react
        run: |
          # Run Jest tests and generate coverage
          npm test -- --coverage --coverageReporters=json --coverageReporters=lcov --coverageReporters=text --coverageReporters=cobertura
          # Create coverage directory in root for artifact upload
          mkdir -p ../coverage
          # Copy test results to expected location
          cp ./jest-junit.xml ../coverage/ui-junit.xml
          # Copy coverage to expected location
          cp ./coverage/cobertura-coverage.xml ../coverage/ui-coverage.xml

      - name: Run ${{ matrix.test-group }} tests
        if: matrix.test-group != 'ui'
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/pyerp_test
          REDIS_URL: redis://localhost:6379/0
          TEST_GROUP: ${{ matrix.test-group }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Create coverage directory
          mkdir -p coverage
          
          # Run tests for specific group from tests directory with coverage
          cd tests && python -m pytest ${{ matrix.test-group }}/ \
            --cov=../pyerp \
            --cov-report=xml:../coverage/${{ matrix.test-group }}-coverage.xml \
            --junitxml=../coverage/${{ matrix.test-group }}-junit.xml \
            -o junit_family=legacy

      - name: Store test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group }}
          path: coverage/*-junit.xml
          retention-days: 14

      - name: Store coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results-${{ matrix.test-group }}
          path: coverage/*-coverage.xml
          retention-days: 14

  upload-results:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: "*-*"
          merge-multiple: true

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: artifacts/*-junit.xml
          name: pyerp-test-results
          fail_ci_if_error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Wilhelm-Schweizer/pyERP
          directory: artifacts/
          fail_ci_if_error: false
          
      - name: Archive all results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: artifacts/
          retention-days: 14
