name: Update Dependencies

on:
  schedule:
    - cron: '0 8 * * 3'  # Run every Wednesday at 8:00 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Update dependencies
      run: |
        python scripts/update_dependencies.py
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update dependencies'
        title: 'Update dependencies'
        body: |
          This PR updates project dependencies to their latest versions.
          
          - Automated dependency updates via pip-tools
          - Please review carefully and test before merging
        branch: dependency-updates
        base: prod  # Target the production branch for dependency updates 